today = true

[aliases]

# usa
la = "america/los_angeles"
mt = "america/boise"
ny = "america/new_york"

# europe
denmark = "europe/copenhagen"
paris = "europe/paris"
uk = "europe/london"
zagreb = "europe/zagreb"
