today = true

[aliases]

# usa
chi = "america/chicago"
la = "america/los_angeles"
mt = "america/boise"
ny = "america/new_york"

# europe
denmark = "europe/copenhagen"
portugal = "europe/lisbon"
paris = "europe/paris"
spain = "europe/madrid"
uk = "europe/london"
zagreb = "europe/zagreb"

# oceania
aet = "australia/sydney"
nz = "pacific/auckland"
