[logging]
severity = "debug"
size-mode = "delete 100 mb"

[battery-status]
app = "upower"
poll-interval = 30
timeout = 5

[battery-percentage]
app = "upower"
repeat-events = [0]
poll-interval = 30
alert = [
  { percent = 50 },
  { percent = 30 },
  { percent = 20, urgency = "critical" },
  { lower = 0, upper = 11, urgency = "critical", timeout = "never" }
]

[[net-interface]]
app = "nmcli"
poll-interval = 30
device = "wlp0s20f3"

[[net-interface]]
app = "nmcli"
poll-interval = 30
device = "enp0s31f6"

[[multiple]]
name = "tailscale"
poll-interval = 300
# repeat-events since we want to be reminded if tailscale is up.
repeat-events = ["true"]
command = """
  set +e
  status=$(tailscale status)
  ec=$?

  if [[ $ec == 0 ]]; then
    echo "(true, $status)"
  else
    echo "(false, $status)"
  fi
"""

[[multiple.trigger-note]]
trigger = "true"
summary = "Tailscale"
body = "Up: \"$out\""
urgency = "normal"
timeout = 10

[[multiple.trigger-note]]
trigger = "false"
summary = "Tailscale"
body = "Down: \"$out\""
urgency = "normal"
timeout = 10
