[logging]
severity = "debug"

[battery-status]
app = "upower"
poll-interval = 30
timeout = 5

[battery-percentage]
app = "upower"
poll-interval = 30
alert = [
  { percent = 50 },
  { percent = 30 },
  { percent = 20, urgency = "critical" },
  { percent = 10, urgency = "critical", timeout = "never" },
  { percent = 9, urgency = "critical", timeout = "never" },
  { percent = 8, urgency = "critical", timeout = "never" },
  { percent = 7, urgency = "critical", timeout = "never" },
  { percent = 6, urgency = "critical", timeout = "never" },
  { percent = 5, urgency = "critical", timeout = "never" },
  { percent = 4, urgency = "critical", timeout = "never" },
  { percent = 3, urgency = "critical", timeout = "never" },
  { percent = 2, urgency = "critical", timeout = "never" },
  { percent = 1, urgency = "critical", timeout = "never" },
  { percent = 0, urgency = "critical", timeout = "never" },
]

[[net-interface]]
app = "nmcli"
poll-interval = 30
device = "wlp0s20f3"

[[net-interface]]
app = "nmcli"
poll-interval = 30
device = "enp0s31f6"
