{
  home.file.".config/zoomus.conf" = {
    # We have this purely to override the default scaleFactor of 1 to 3
    # (for HiDPI). All other settings have been autogenerated.
    source = ./zoomus.conf;
  };
}
