name: nixfmt

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3ba49889a76539ea0f7d7285b203e7f81326ded.tar.gz:nixos-config=configuration.nix

      - name: Check style
        run: nix-shell shell.nix --command "nixpkgs-fmt --check ./"
